.PHONY: test tck-test tck-properties up-d

# Metadata for tck_results.properties; override on the command line, e.g.
#   make tck-test TCK_VENDOR_NAME="Acme" TCK_PRODUCT_VERSION=1.0.0
TCK_VENDOR_NAME ?= binary141
TCK_VENDOR_URL ?= https://github.com/binary141
TCK_PRODUCT_NAME ?= Godecide
TCK_PRODUCT_URL ?= https://github.com/binary141/Godecide
TCK_PRODUCT_VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
TCK_PRODUCT_COMMENT ?= DMN engine written in Go with a FEEL interpreter.
TCK_INSTRUCTIONS_URL ?= https://github.com/binary141/Godecide/blob/main/TCK.md


up-d:
	docker compose up -d

# Unit tests for everything except the generated TCK suite in ./tests.
test:
	@go test -v $$(go list ./... | grep -v '^Godecide/tests$$') 2>&1 | tee dmn_test_output; \
	passed=$$(grep -c "^--- PASS" dmn_test_output || true); \
	failed=$$(grep -c "^--- FAIL" dmn_test_output || true); \
	echo ""; \
	echo "Results: $$passed passed, $$failed failed"

# DMN TCK compliance suite (generated by cmd/gentests). Also writes
# tck_results.csv in the format the dmn-tck repo expects for submissions.
tck-test: tck-properties
	@TCK_RESULTS_CSV=$$(pwd)/tck_results.csv go test -v ./tests 2>&1 | tee dmn_tck_test_output; \
	passed=$$(grep -c "^--- PASS" dmn_tck_test_output || true); \
	failed=$$(grep -c "^--- FAIL" dmn_tck_test_output || true); \
	skipped=$$(grep -c "^--- SKIP" dmn_tck_test_output || true); \
	echo ""; \
	echo "TCK results: $$passed passed, $$failed failed, $$skipped skipped"

# Writes tck_results.properties, the metadata file submitted next to tck_results.csv.
tck-properties:
	@printf '%s\n' \
		'vendor.name=$(TCK_VENDOR_NAME)' \
		'vendor.url=$(TCK_VENDOR_URL)' \
		'product.name=$(TCK_PRODUCT_NAME)' \
		'product.url=$(TCK_PRODUCT_URL)' \
		'product.version=$(TCK_PRODUCT_VERSION)' \
		'product.comment=$(TCK_PRODUCT_COMMENT)' \
		'last.update=$(shell date +%F)' \
		'instructions.url=$(TCK_INSTRUCTIONS_URL)' > tck_results.properties
