.PHONY: test tck-test up-d

up-d:
	docker compose up -d

# Unit tests for everything except the generated TCK suite in ./tests.
test:
	@go test -v $$(go list ./... | grep -v '^dmn/tests$$') 2>&1 | tee dmn_test_output; \
	passed=$$(grep -c "^--- PASS" dmn_test_output || true); \
	failed=$$(grep -c "^--- FAIL" dmn_test_output || true); \
	echo ""; \
	echo "Results: $$passed passed, $$failed failed"

# DMN TCK compliance suite (generated by cmd/gentests).
tck-test:
	@go test -v ./tests 2>&1 | tee dmn_tck_test_output; \
	passed=$$(grep -c "^--- PASS" dmn_tck_test_output || true); \
	failed=$$(grep -c "^--- FAIL" dmn_tck_test_output || true); \
	skipped=$$(grep -c "^--- SKIP" dmn_tck_test_output || true); \
	echo ""; \
	echo "TCK results: $$passed passed, $$failed failed, $$skipped skipped"
